version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/balloon/auth
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - restore_cache:
          key: mod-{{ checksum "go.sum" }}
      - run:
          name: install dependencies
          command: cd cmd/ && go get
      - run:
          name: unit test
          command: go test -v ./...
      - save_cache:
          key: mod-{{ checksum "go.sum" }}
          paths:
            - $GOPATH/pkg/mod

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
